### ISSUE TITLE
Wrong argument with the new update notifications for the embed's author

### ISSUE THREAD

**Issue by ghost** [thatmaxplayle/HangoutBotPublic#7]
**Describe the bug**
Author image with the new update notifications is set to a link instead of a image

**To Reproduce**
1. Click on the author
![afbeelding](https://user-images.githubusercontent.com/79423040/131540840-12a7d9a1-b349-48d9-b344-395c233d7553.png)
2. Click on the name
3. A imgur link shows up

**Expected behavior**
An author image next to the name

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/79423040/131540951-b83f4e1f-6a6a-42ee-997a-60baa376519e.png)

**Comment by maxplayle04** [comment]
Thanks for letting us know, I'll get this sorted now.

**Comment by maxplayle04** [comment]
This issue has been fixed in HangoutBot v3.0.6.1174 and is being served publicly now.
